version: '1'

services:
  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - ./mongo-data:/data/db
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  # mysql-shop:
  #   image: mysql:latest
  #   container_name: my-mysql-shop
  #   ports:
  #     - '3307:3306' # 3306 port mặc định của mysql -> mapping use 3307
  #   # env_file:
  #   #   - .env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123
  #     # - MYSQL_PASSWORD=123
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql
  #     - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
       - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    # env_file:
    #   - .env
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=12345
      - RABBITMQ_PLUGINS=rabbitmq_management
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

networks:
  default:
    driver: bridge
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
