version: '1'

services:
  # mongo:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - ./mongo-data:/data/db
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}


  mysql-shop:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3307:3306"       # 3306 port mặc định của mysql -> mapping use 3307
    # env_file:
    #   - .env
    environment:
      - MYSQL_ROOT_PASSWORD=123
      # - MYSQL_PASSWORD=123
    volumes:
      - ./mysql-data:/var/lib/mysql


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    # env_file:
    #   - .env
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=12345
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq



networks:
  default:
    driver: bridge
